# Generated by Django 4.2.1 on 2023-05-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('НП', 'Новая Почта'), ('УП', 'Укрпошта')], default='НП', max_length=2, verbose_name='Способ доставки*')),
                ('year_in_school2', models.CharField(choices=[('НП', 'Забрать в отделении'), ('УП', 'Доставка курьером')], default='НП', max_length=2, verbose_name='')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='Имя*')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Фамилия*')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='Адрес')),
                ('postal_code', models.IntegerField(default='', verbose_name='Номер отделения*')),
                ('postal_code2', models.CharField(default='+380', max_length=20, verbose_name='Телефон*')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Город*')),
                ('city2', models.TextField(blank=True, default='', verbose_name='Коментарий')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
