# Generated by Django 4.2.1 on 2023-05-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('glavnoe_photo', models.ImageField(default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcherk', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка подчёркивания')),
                ('text', models.CharField(max_length=35000, null=True, verbose_name='Текст внизу')),
                ('title', models.CharField(max_length=150, verbose_name='Название страницы')),
                ('description', models.CharField(max_length=150, verbose_name='Мета описание')),
                ('keywords', models.CharField(max_length=150, verbose_name='Мета слова')),
                ('fotertitle', models.CharField(max_length=350, verbose_name='Заголовок в футере')),
                ('fotercontent', models.CharField(max_length=550, verbose_name='Слова в футере')),
                ('logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок 1 слайда')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото 1 слайда')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(default=None, max_length=6, null=True, verbose_name='Номер категории')),
                ('stock', models.PositiveIntegerField(default=1, null=True)),
                ('name', models.CharField(db_index=True, default=None, max_length=200)),
                ('slug', models.SlugField(default=None, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('dopolnitelnie_xapakteristiki', models.CharField(default=None, max_length=2550, null=True, verbose_name='Дополнительные характеристики')),
                ('polnoe_opisanie', models.CharField(default=None, max_length=10000, verbose_name='Полное описание')),
                ('description', models.CharField(blank=True, default=None, max_length=150, verbose_name='Мета описание')),
                ('keywords', models.CharField(blank=True, default=None, max_length=150, verbose_name='Мета слова')),
                ('glavnoe_photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото')),
                ('photo_na_slider', models.ImageField(default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото на слайдер')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('num', models.CharField(max_length=10, null=True, verbose_name='Номер слайда')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['title'],
            },
        ),
    ]
